### PR TITLE
telemetry decorator, staggering

### LINKED ISSUE #117: [Telemetry] - Switch to custom frequency publishing for all measurements
### Description

Right now, we basically publish on a loop with a time of wait inbetween X.

### Acceptance Criteria

- Each measurement can have its own frequency of measurement and publishing
- These frequencies are spread out in their starting by a couple ms

### Proposed Solution

Perhaps launching a thread which calls each function on a specified frequency and the callback from such is passed to a function to serialize and publish.  This could result in reorganization of the whole project, and that is OK.

### PR DESCRIPTION
**Pull request by starmut**
## Changes

Added a `@measurement(ms)` decorator to make it easier to add further measurements and run them at custom frequencies.

Also staggers beginning measurements over the first second of execution.

## Notes

Not tested at all since I couldn't figure out how to get it to run.

## To Do

_Any remaining things that need to get done_

- [ ] See if it works

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #117.

### CODE REVIEW

**Comment by jr1221** [comment]
Looks nice to use will test tmrw.  Also will fixup imports, they need to be right in pyproject.toml for hardware deployment but not your concern.  If you want to keep working on that [other issue I mentioned](https://github.com/Northeastern-Electric-Racing/Odysseus/issues/52) please lmk.

**Comment by jr1221** [comment]
I don't know if this can work in its current form.  Basically while fixing the dependencies I noticed that since each poll_data file ( ex. example.py) requires `measurement` it must import `telemetry`.  But `telemetry` must import `example` in order to populate routines with the functions in poll_data.  Any ideas?

**Comment by starmut** [comment]
The decorator (and routines dict) could be in its own module isolated from either `publish.py` or the specific measurement functions. Then `examples.py` and `publish.py` both import `decorator.py`. Theoretically this should work?

(I have no idea how modules work in python btw, I'm used to JS supporting circular dependencies)

**Comment by jr1221** [comment]
The problem is `example.py` imports `decorator.py` but due to the routines dict the `example.py` must also be imported by `decorator.py`. 

I want this to work so bad, maybe switching to OOP may allow it to work?  Like if a measurement class existed with the properties `frequency`, `topic`, `unit`, a function `fetch_data` and then `set_inverval` could take in this object and await the result.  Then `set_interval` could serialize and publish the data accordingly?

**Comment by starmut** [comment]
> I don't know if this can work in its current form. Basically while fixing the dependencies I noticed that since each poll_data file ( ex. example.py) requires `measurement` it must import `telemetry`. But `telemetry` must import `example` in order to populate routines with the functions in poll_data. Adn this causes a circular dependency. Any ideas?
> 
> Edit: Idgaf about if the pyproject.toml works if your code can work in a certain structure of folders then I will abandon the pyproject.toml.

Can you show me how `telemetry` needs to import `example`? I don't see why it should. `publish` and `example` both import different parts of `__init__.py` (which I tried to make into a separate file). I think there doesn't need to be any circular import here.

**Comment by starmut** [comment]
Also, can you actually send me a command and the directory to run it in, it would be easier if I can just see the issue you're talking about.

**Comment by jr1221** [comment]
The telemetry package needs to populate the routines dict correct?  Oh wait I see you may be right.  Do you mind if I fix the imports (the stuff that messed up ur install not the possible circular stuff) and push?  I'll also send the command rn.

**Comment by jr1221** [comment]
Here is the command (run in same directory as `pyproject.toml`)
`python -m telemetry.publish`


I am getting routines is zero length.  Pushed my changes, I removed function as it is not a valid type hint:(

**Comment by starmut** [comment]
Simply adding `from .poll_data import can, example, halow` made it populate the dict with no issues.
However it's not responding to ctrl-c to stop running anymore, and `set_interval` probably needs to do the actual publishing.

**Comment by jr1221** [comment]
Sweet!  Ya my b I thought we needed to set the routines.  If you see if STOP.set() logic in `publish`, perhaps just check the state of that each time in `set_interval` it would be ugly but should exit nice.  Also for publishing just copy the logic from b4 ur PR, perhaps set_interval should be in publish so it can reference the publisher code?  Tbh I do not know about the thread safety needed on all of these objects.

**Comment by starmut** [comment]
I think it works now? Spams my console with errors saying it failed to fetch something or other, but I assume that's good. Especially given the _speed_ of that spam.

**Comment by jr1221** [comment]
Yup it looks great.  I even printed the current time in ms when publishing, and it is indeed pretty close to the right number of miliseconds.  It is about 118ms for a 100, and 60-65ms for a 50ms call.  That is actually amazing for python lol.  Great job, I will commit the actual frequencies, officially review, etc. tommorow.  Again awesome.  If you wanna do more before break lmk and I can start a slack thread:)

**Review by jr1221 — APPROVED** [review]
tested on non-tpu pi and works.
sorry also hijacked ur pr for a measurement that was missing lol.

**Pull request merged**
